# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do 
  desc "Description of what the lane does"
  lane :build do |options|
    scheme = options[:scheme]

    gym(
        scheme: scheme,
	export_method: "development",
	skip_codesigning: true,
	skip_package_ipa: true,
         clean: true)
  end
  lane :tests do |options|
    scheme = options[:scheme]
    run_tests(scheme: 'JenkinsStudy')
  end
end
